"""empty message

Revision ID: 29a55cbdcc88
Revises: 
Create Date: 2018-10-31 21:51:42.638012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a55cbdcc88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_column('blog', 'owner_id')
    # ### end Alembic commands ###
